services:
  srb2kart:
    # Ref: https://github.com/rwanyoike/srb2kart-server-docker
    image: "docker.io/rwanyoike/srb2kart-server:latest"
    command:
      - "-dedicated"
      - "-file"
      - "addons/KL_HOSTMOD_V18.pk3" # https://mb.srb2.org/showthread.php?t=45107
      - "addons/KL_kartmp-v1.5.pk3" # https://mb.srb2.org/showthread.php?t=47203
      - "addons/kl_DynMusic-v3.wad" # https://mb.srb2.org/showthread.php?t=45382
      - "addons/KL_MiniRankingPlus-v3.1.pk3" # https://mb.srb2.org/showthread.php?t=47312
      - "addons/kl_hitfeed-v2.2.pk3" # https://mb.srb2.org/showthread.php?t=45269
      - "addons/KL_HORNMOD-CE_V2.pk3" # https://mb.srb2.org/showthread.php?t=44634
      - "addons/KL_Acrobatics-v0.5a.pk3" # https://mb.srb2.org/showthread.php?t=47566
      - "addons/kl_driftgauge_v2.wad" # https://mb.srb2.org/showthread.php?t=45235
      - "addons/KL_KartExhaust_v4.pk3" # https://mb.srb2.org/showthread.php?t=48207
      - "addons/KRB_IP-v2.1.pk3" # https://mb.srb2.org/showthread.php?t=44856
      - "addons/KR_milkpack-v1.1.pk3" # https://mb.srb2.org/showthread.php?t=46697
      - "addons/krl_NightmarePack_v4.pk3" # https://mb.srb2.org/showthread.php?t=44285
      - "addons/KRL_SparkCup_V3.pk3" # https://mb.srb2.org/showthread.php?t=45405
      - "addons/KL_Frenchorns_v1.3.pk3" # ???
      - "bonuschars.kart" # https://mb.srb2.org/showthread.php?t=43708
    volumes:
      - "${PWD}/data:/data"
    ports:
      - "5029:5029/udp"
